import type { Family } from "./catalog";

/** Values are schema sentinels only. `qualitativeOnly` must suppress quantitative
 * material-property UI and any engineering calculation for these entries. */
export const additionalBases = [
  { name: "Rigid photopolymer", e: 1, rho: 1, qualitativeOnly: true, color: "#d7dde3", intro: "Rigid printable polymer for qualitative mechanism studies only." },
  { name: "Spring steel", e: 1, rho: 1, qualitativeOnly: true, color: "#66717e", intro: "Elastic metal strip for qualitative flexure demonstrations only." },
  { name: "Carbon-fibre composite", e: 1, rho: 1, qualitativeOnly: true, color: "#36434d", intro: "Directional composite strut material for qualitative demonstrations only." },
  { name: "Invar", e: 1, rho: 1, qualitativeOnly: true, color: "#aeb7be", intro: "Low-expansion alloy used only as a qualitative contrast material." },
  { name: "Fused silica", e: 1, rho: 1, qualitativeOnly: true, color: "#eaf3f6", intro: "Transparent glass support represented qualitatively only." },
  { name: "Silicon nitride", e: 1, rho: 1, qualitativeOnly: true, color: "#c6d2d9", intro: "Thin dielectric layer represented qualitatively only." },
  { name: "GST phase-change film", e: 1, rho: 1, qualitativeOnly: true, color: "#765b73", intro: "Switchable optical film represented qualitatively only." },
  { name: "Liquid crystal", e: 1, rho: 1, qualitativeOnly: true, color: "#b9d8d0", intro: "Field-addressed optical medium represented qualitatively only." },
  { name: "Graphene", e: 1, rho: 1, qualitativeOnly: true, color: "#29333a", intro: "Atomically thin conducting layer represented qualitatively only." },
  { name: "Air", e: 1, rho: 1, qualitativeOnly: true, color: "#dbeaf3", intro: "Functional wave medium, never a structural substitute." },
  { name: "Paraffin phase-change medium", e: 1, rho: 1, qualitativeOnly: true, color: "#f4df9c", intro: "Thermal-storage phase represented qualitatively only." },
  { name: "PZT ceramic", e: 1, rho: 1, qualitativeOnly: true, color: "#d8c4b8", intro: "Piezoelectric patch represented qualitatively only." },
  { name: "NdFeB magnet", e: 1, rho: 1, qualitativeOnly: true, color: "#5e6673", intro: "Fixed-magnetization inclusion represented qualitatively only." },
] as const;

export type ExpandedFamily = Family & {
  summary: string;
  tryPrompt: string;
  limitations: string;
  controlNote: string;
};

type Draft = Omit<ExpandedFamily, "origin" | "mechanism" | "behavior" | "applicationLesson" | "applicationWhy" | "variants" | "variantLessons" | "defaultBase" | "defaultSecondary" | "allowedBase" | "allowedSecondary"> & {
  purpose: string; structure: string; behaviorText: string; why: string; usecase: string;
  variants: [string, string][]; base: number; secondary?: number; role?: string;
  required?: boolean; fixed?: boolean; materialNote: string;
};

const f = (d: Draft): ExpandedFamily => ({
  id: d.id, name: d.name, category: d.category, tag: d.tag, color: d.color, source: d.source,
  origin: `Purpose: ${d.purpose}`,
  mechanism: `Structure: ${d.structure}`,
  behavior: `Behavior: ${d.behaviorText}`,
  application: d.application,
  applicationLesson: d.usecase,
  applicationWhy: d.why,
  variants: d.variants.map(([name]) => name),
  variantLessons: d.variants.map(([name, lesson]) => `${name}: ${lesson}`),
  defaultBase: d.base, defaultSecondary: d.secondary ?? d.base,
  allowedBase: [d.base], allowedSecondary: d.secondary === undefined ? [] : [d.secondary],
  secondaryRole: d.role, secondaryRequired: d.required, secondaryFixed: d.fixed,
  materialNote: d.materialNote, summary: d.summary, tryPrompt: d.tryPrompt,
  limitations: d.limitations, controlNote: d.controlNote,
});

/** Thirty qualitative, source-linked teaching families. This is structurally
 * compatible with Family[] while retaining learning copy used by the expansion UI. */
export const expandedFamilies: ExpandedFamily[] = [
  f({ id:"pentamode", name:"Pentamode lattice", category:"Mechanical", tag:"Stiff in compression, compliant in shear", color:"#99b9ca", source:"https://doi.org/10.1063/1.4709436", base:18,
    purpose:"show how a connected solid can be shaped to resist compression much more readily than shear.", structure:"slender double-cone links meet at diamond-like nodes; the necks control the compliant connection.", behaviorText:"the network can support a pressure-like load while its joints permit shear-like distortion in this qualitative model.", application:"Transformation-acoustics research cell", usecase:"A printed cell is used in a laboratory array to explore how geometry guides pressure-wave paths.", why:"Its link geometry offers a route to material responses that a uniform block cannot provide.", variants:[["Uniform diamond","Same neck geometry repeats through the cell."],["Fine necks","Narrower illustrated junctions emphasise hinge-like motion."],["Graded necks","Junction appearance changes across the cell to introduce a spatial pattern."]], summary:"A connected lattice uses narrow nodes to separate compression-dominated and shear-dominated motion.", tryPrompt:"Compare broad and fine necks while shearing the view.", limitations:"An ideal pentamode response is not reached by this display; fabrication defects and scale matter.", controlNote:"Neck style is a qualitative geometry control, not a stiffness prediction.", materialNote:"One rigid photopolymer represents the complete lattice; no secondary phase is implied." }),
  f({ id:"rotating-squares", name:"Rotating squares", category:"Mechanical", tag:"Rigid tiles joined by compliant corners", color:"#f0ae79", source:"https://doi.org/10.1080/00268970010009332", base:18, secondary:0, role:"TPU corner hinges", required:true, fixed:true,
    purpose:"show an auxetic mechanism built from nearly rigid tiles and flexible corner connections.", structure:"square panels meet only at their corners, where small flexible ligaments let each panel rotate.", behaviorText:"opening the hinges makes the tiled patch expand in two in-plane directions together.", application:"Conforming protective-insert concept", usecase:"A tile-and-hinge patch can be placed in a flexible guard so it opens around a curved joint.", why:"Rotation creates a large visible shape change without stretching every tile.", variants:[["Square patch","A compact grid makes simultaneous tile rotation easy to see."],["Narrow strip","A single band isolates the edge behaviour."],["Diamond patch","A rotated outline shows that boundary shape changes the visible motion."]], summary:"Corner hinges turn rigid-square rotation into a widening sheet.", tryPrompt:"Drag the opening control and watch both patch dimensions change.", limitations:"Real hinges fatigue and tile contact eventually limits rotation.", controlNote:"Opening is an illustrative kinematic state, not a force or strain calculation.", materialNote:"Rigid photopolymer tiles and TPU hinges are fixed parts with distinct roles, never a blended material." }),
  f({ id:"chiral-honeycomb", name:"Chiral honeycomb", category:"Mechanical", tag:"Ring rotation through tangent ligaments", color:"#d9a3cb", source:"https://doi.org/10.1016/S0020-7403(99)00007-5", base:18, secondary:0, role:"TPU tangent ligaments", required:true, fixed:true,
    purpose:"show how handed ring-and-ligament cells couple stretching with rotation.", structure:"circular nodes connect by ligaments tangent to each ring, giving each cell a right- or left-handed layout.", behaviorText:"pulling a patch can rotate the rings and produce a directional, handed deformation.", application:"Twist-sensitive soft-gripper concept", usecase:"A chiral sheet can be studied as a surface that changes shape as a gripper closes.", why:"Handed geometry gives designers a simple way to study coupled twist and extension.", variants:[["Right handed","All tangential ligaments follow one circulation."],["Left handed","The ligament circulation is mirrored."],["Alternating rows","Handedness alternates to compare local and global rotation."]], summary:"Tangent ligaments make the ring arrangement respond differently when its handedness is reversed.", tryPrompt:"Switch handedness, then compare the ring-rotation direction.", limitations:"This visual model does not predict torsional or in-plane material properties.", controlNote:"Handedness selects geometry only; no performance ranking is implied.", materialNote:"Rigid printed rings are connected by fixed TPU ligaments; both roles are intentionally separate." }),
  f({ id:"miura-origami", name:"Miura origami", category:"Mechanical", tag:"Folded facets that deploy together", color:"#91c6b9", source:"https://doi.org/10.1016/0020-7683(85)90025-4", base:18, secondary:0, role:"TPU crease hinges", required:true, fixed:true,
    purpose:"teach coordinated folding in a tessellated sheet.", structure:"parallelogram panels repeat along mountain and valley crease lines, so neighbouring facets constrain each other.", behaviorText:"changing the fold state expands or contracts the pattern while the facets rotate around their creases.", application:"Deployable solar-array concept", usecase:"A folded panel pattern is used to explain how a compact surface can open into a larger one.", why:"One crease motion coordinates many facets, making deployment easy to observe.", variants:[["Acute facets","A 55° sector layout gives a sharp zig-zag."],["Balanced facets","A 65° layout provides a middle comparison."],["Open facets","A 75° layout broadens the projected pattern."]], summary:"Repeated parallelogram facets turn a local fold into coordinated sheet deployment.", tryPrompt:"Move the fold state between compact and open.", limitations:"Panel thickness, crease stiffness, and self-contact are outside this lesson.", controlNote:"Sector angle and fold state describe geometry, not deployment force.", materialNote:"Rigid printed panels use fixed TPU crease hinges; no mixed phase is represented." }),
  f({ id:"kirigami", name:"Kirigami ribbon sheet", category:"Mechanical", tag:"Cuts release out-of-plane motion", color:"#d4d280", source:"https://doi.org/10.1038/nmat4082", base:18,
    purpose:"show how patterned cuts allow a sheet to stretch and buckle into a new shape.", structure:"slits divide a continuous sheet into connected ribbons while leaving bridge regions intact.", behaviorText:"tension can open the cuts and let ribbons rotate or lift out of the sheet plane.", application:"Stretchable-sensor substrate concept", usecase:"A cut sheet is used as a visual analogue for electronics that must follow a moving surface.", why:"Cuts localize deformation so the remaining material can move more freely.", variants:[["Single bow","One cut row demonstrates the basic opening motion."],["S-shaped ribbons","Alternating curves introduce a reversible-looking path."],["Three-lobe ribbons","Three linked lobes show a denser cut topology."]], summary:"Strategic cuts make a sheet transform through ribbon rotation rather than uniform stretching.", tryPrompt:"Increase opening and inspect where the ribbon bridges remain connected.", limitations:"Tear initiation and out-of-plane buckling depend on thickness and edge details.", controlNote:"Cut pattern and opening are illustrative states only.", materialNote:"A single rigid-photopolymer sheet represents the cut pattern; it has no selectable secondary material." }),
  f({ id:"bistable-beam", name:"Bistable beam", category:"Mechanical", tag:"Snap-through between two shapes", color:"#768fa3", source:"https://arxiv.org/abs/1612.05988", base:19, secondary:2, role:"Aluminium clamps", required:true, fixed:true,
    purpose:"show a curved elastic member with two resting configurations.", structure:"spring-steel arches are held between rigid aluminium end clamps, creating a shallow snap-through path.", behaviorText:"pushing past an intermediate shape can switch the arch between two illustrated stable states.", application:"Mechanical-memory concept demonstrator", usecase:"A row of arches is used to explain how a structure can visibly retain a switched shape after loading is removed.", why:"Bistability can store a geometry state without continuous actuation.", variants:[["Shallow arches","Low-curvature arches provide the starting shape."],["Deep arches","More pronounced arches show a different snap path."],["Paired arches","Two arches illustrate coupled switching."]], summary:"A restrained curved beam can snap between two qualitative resting shapes.", tryPrompt:"Toggle the arch state and compare shallow with deep profiles.", limitations:"Actual snap load, fatigue, and stability need physical testing.", controlNote:"State selects an illustrated configuration; it does not calculate a switching threshold.", materialNote:"Spring-steel arches are clamped by fixed aluminium pieces, not combined as an alloy." }),
  f({ id:"tensegrity", name:"Tensegrity cell", category:"Mechanical", tag:"Isolated struts held by tension network", color:"#55737b", source:"https://doi.org/10.1109/ROBOT.2009.5152752", base:20, secondary:16, role:"Steel tension cables", required:true, fixed:true,
    purpose:"teach a structure whose compression members do not touch one another.", structure:"carbon-fibre struts float inside a closed network of tension-only steel cables.", behaviorText:"changing cable geometry redistributes the visible shape while the struts remain separated.", application:"Lightweight deployable-structure concept", usecase:"A small tensegrity cell helps learners inspect how a cable network holds rigid members in place.", why:"The division of tension and compression creates an unusually open load-bearing form.", variants:[["Three struts","A minimal prism makes cable paths easy to trace."],["Four struts","An added compression member changes the network topology."],["Five struts","A denser set of separated struts highlights connectivity."]], summary:"Cables stabilize separated struts through a self-stressed geometry.", tryPrompt:"Rotate the cell and trace one cable from end to end.", limitations:"Pretension, joints, and cable slack determine real behaviour and are not modelled.", controlNote:"Strut count changes topology only; no strength claim follows.", materialNote:"Carbon-fibre struts and steel cables are fixed role-specific components." }),
  f({ id:"spinodal-shell", name:"Spinodal shell", category:"Mechanical", tag:"Smooth random-looking connected shell", color:"#b1c8d9", source:"https://arxiv.org/abs/1904.06733", base:18,
    purpose:"show a shell architecture inspired by phase-separation morphology rather than a periodic unit cell.", structure:"a continuous smooth surface divides winding void regions; shell thickness is illustrated separately from the void network.", behaviorText:"the connected shell spreads deformation through curved paths without a preferred lattice direction in the balanced view.", application:"Lightweight energy-absorption research coupon", usecase:"A printed coupon lets researchers compare a smooth shell topology with beam lattices.", why:"Its continuous curved network avoids repeated sharp joints and can be made directionally biased.", variants:[["Balanced spectrum","Comparable features appear in every direction."],["Layer-biased spectrum","The field is stretched to favour a layered appearance."],["Column-biased spectrum","The field is stretched in a second direction to form columns."]], summary:"A phase-separation-like field becomes a continuous shell with controllable directional appearance.", tryPrompt:"Switch the bias and look for the direction in which the voids elongate.", limitations:"This display cannot estimate stiffness, strength, or defect tolerance.", controlNote:"Bias is a qualitative topology setting, not an engineered density specification.", materialNote:"The entire shell is one rigid photopolymer teaching material." }),
  f({ id:"chainmail", name:"Chainmail sheet", category:"Mechanical", tag:"Interlocking links that drape together", color:"#8c9297", source:"https://doi.org/10.1038/s41586-021-03698-7", base:16,
    purpose:"show how interlocking rigid links can move freely when loose and resist rearrangement when crowded.", structure:"closed steel loops pass through neighbouring loops to form a flexible, non-woven sheet.", behaviorText:"the links can drape and reorient; contact between many links can restrict local motion.", application:"Conforming protective-garment concept", usecase:"A linked patch is used to inspect the difference between a free-hanging curtain and a compacted arrangement.", why:"It covers curved shapes while retaining a path to mechanically restricted states.", variants:[["Linked patch","A square field makes the interlock pattern visible."],["Narrow curtain","A hanging strip emphasizes drape."],["Offset drape","Shifted rows show how boundaries alter the sheet."]], summary:"Interlocked loops make a material-like sheet without a woven fibre mesh.", tryPrompt:"Compare the relaxed patch with the offset drape.", limitations:"Friction, contact force, and jamming are not computed.", controlNote:"Drape pose is visual only; it is not a predicted stiffness state.", materialNote:"One steel link material is used throughout; there is no secondary material." }),
  f({ id:"thermal-expansion", name:"Bimetal thermal-expansion strip", category:"Mechanical", tag:"Bonded layers curve with temperature change", color:"#b6ad91", source:"https://doi.org/10.1088/1367-2630/15/4/045033", base:2, secondary:21, role:"Invar layer", required:true, fixed:true,
    purpose:"show how two bonded materials with different expansion tendencies create curvature.", structure:"an aluminium layer is permanently bonded to an Invar layer along a long strip.", behaviorText:"a temperature change is represented as a qualitative bend toward one side because the layers want to change length differently.", application:"Passive thermal-switch concept", usecase:"A layered strip can be used in a classroom model of a temperature-responsive contact or vent.", why:"The response comes from the layered geometry and material contrast, without motors or electronics.", variants:[["Equal layers","Both visible layers share the same width."],["Aluminium rich","The aluminium side occupies more of the strip."],["Invar rich","The Invar side occupies more of the strip."]], summary:"Bonded layers transform unequal thermal expansion tendencies into bending.", tryPrompt:"Toggle the temperature direction and inspect the bend direction.", limitations:"Temperature, curvature, and stress are intentionally not calculated.", controlNote:"Layer ratio is qualitative and must not be presented as a calibration.", materialNote:"Aluminium and Invar remain fixed bonded layers rather than a volume blend." }),
  f({ id:"negative-index", name:"Negative-index split-ring array", category:"Electromagnetic", tag:"Coupled electric and magnetic resonators", color:"#c98c69", source:"https://doi.org/10.1103/PhysRevLett.84.4184", base:5, secondary:8, role:"FR-4 support board", required:true, fixed:true,
    purpose:"introduce a microwave unit cell whose patterned conductors can create a narrow resonant response.", structure:"copper split rings and companion traces sit on a fiberglass-epoxy board; their gaps and loops form coupled resonators.", behaviorText:"near a designed microwave band, the array can exhibit an effective response unlike either ingredient alone.", application:"Microwave wave-control research sample", usecase:"A board is measured between microwave antennas to study how a resonant pattern changes transmission.", why:"It connects a visible printed pattern to electromagnetic resonance.", variants:[["Single split rings","One ring motif establishes the basic gap-and-loop cell."],["Nested split rings","Concentric loops compare coupled resonator geometry."],["Alternating gaps","Gap direction alternates across cells to show orientation."]], summary:"Printed resonators can create a narrow, geometry-dependent microwave response.", tryPrompt:"Switch the ring pattern and inspect the location of every gap.", limitations:"Negative index is frequency-, direction-, and retrieval-method dependent; it is not shown or calculated here.", controlNote:"Ring style is a geometry comparison, not an index prediction.", materialNote:"Copper traces are fixed on an FR-4 support; the board is not a copper mixture." }),
  f({ id:"epsilon-near-zero", name:"Epsilon-near-zero channel", category:"Electromagnetic", tag:"Wave phase through a narrow throat", color:"#c8bd8e", source:"https://doi.org/10.1103/PhysRevLett.100.033903", base:5, secondary:27, role:"Air-filled channel", required:true, fixed:true,
    purpose:"show a microwave channel geometry used to study near-zero effective permittivity transmission.", structure:"copper walls bound an air-filled narrow throat with a fixed visual width and changing longitudinal profile.", behaviorText:"at an appropriate operating condition, a specially designed channel can show an unusually uniform phase progression through the constriction.", application:"Microwave channel experiment", usecase:"A waveguide coupon is used to compare a regular path with a constricted path under controlled excitation.", why:"The example makes waveguide geometry and boundary conditions visible.", variants:[["Uniform throat","The air channel keeps one illustrated width."],["Stepped throat","The throat changes between discrete sections."],["Central constriction","A central neck concentrates the visible geometry."]], summary:"A bounded air channel provides a qualitative model of ENZ tunnelling experiments.", tryPrompt:"Compare the three throat profiles without interpreting them as bandwidth results.", limitations:"ENZ behavior requires a specific mode and frequency and cannot be inferred from the shape alone.", controlNote:"Throat profile is fixed-width teaching geometry, not a transmission calculation.", materialNote:"Copper walls bound functional air; air is not offered as a structural material." }),
  f({ id:"photonic-bandgap", name:"Photonic-bandgap crystal", category:"Optical", tag:"Periodic pillars block selected light paths", color:"#9fc1da", source:"https://doi.org/10.1016/S0167-9317(02)00623-8", base:4, secondary:22, role:"Fused-silica substrate", required:true, fixed:true,
    purpose:"show how repeated dielectric pillars create a photonic crystal.", structure:"silicon pillars repeat on a fused-silica support; a missing or changed pillar introduces a defect path.", behaviorText:"periodicity can prohibit some light modes while defects can localize or route selected modes.", application:"Integrated optical-waveguide research study", usecase:"A patterned chip region is used to explain why a line defect can guide light through a crystal.", why:"It gives a clear structural route from periodic order to controlled optical paths.", variants:[["Periodic crystal","A complete pillar array provides the reference pattern."],["Line defect","One pillar row is removed to show a route."],["Point defect","A local change creates a confined feature."]], summary:"Periodic silicon pillars and deliberate defects form a map for light on a chip.", tryPrompt:"Toggle the defect and trace the intended path through the pillars.", limitations:"Bandgaps depend on wavelength, polarization, dimensions, and substrate; none are calculated.", controlNote:"Defect choice is qualitative topology only.", materialNote:"Silicon pillars are fixed to fused silica, not mixed with the glass." }),
  f({ id:"bound-state-continuum", name:"Quasi-BIC metasurface", category:"Optical", tag:"Asymmetry releases a trapped resonance", color:"#b8a6d9", source:"https://doi.org/10.1103/PhysRevLett.121.193903", base:4, secondary:22, role:"Fused-silica substrate", required:true, fixed:true,
    purpose:"illustrate how a small symmetry break can couple a high-Q-like optical mode to free space.", structure:"paired silicon bars sit on glass; unequal length, tilt, or width breaks the symmetric arrangement.", behaviorText:"the qualitative resonance becomes observable when symmetry breaking allows the otherwise protected mode to couple out.", application:"Narrow-feature optical sensing research", usecase:"A metasurface coupon is scanned optically to study how asymmetry changes a resonance feature.", why:"Small geometric differences provide a compact design handle for resonant light control.", variants:[["Unequal lengths","One bar is visibly shorter."],["Opposite tilts","The pair is rotated in opposite directions."],["Unequal widths","One bar is visibly wider."]], summary:"Deliberate asymmetry provides a readable route to a quasi-bound optical resonance.", tryPrompt:"Cycle through the symmetry breaks and identify what is no longer mirrored.", limitations:"Quality factor, loss, and fabrication tolerance are not predicted.", controlNote:"Asymmetry type is descriptive only; it does not set a resonance value.", materialNote:"Silicon features remain fixed on a fused-silica support." }),
  f({ id:"phase-change", name:"Phase-change metasurface", category:"Optical", tag:"Reconfigurable GST optical pixels", color:"#a97891", source:"https://www.nature.com/articles/s41467-022-29374-6", base:24, secondary:22, role:"Fused-silica support", required:true, fixed:true,
    purpose:"show an optical surface whose pixel material can be switched between qualitative states.", structure:"GST pixels sit on glass above a fixed, non-selectable heater layout.", behaviorText:"changing the GST state changes how the patterned pixels interact with light in a qualitative depiction.", application:"Reconfigurable optical test chip", usecase:"A test chip is used to explain how local heating can program optical pixels after fabrication.", why:"One patterned surface can be revisited with more than one optical state.", variants:[["Uniform pixels","All GST regions share one visible state."],["Alternating pixels","Neighbouring pixels alternate to show coding."],["Graded pixels","Pixel state changes gradually across the surface."]], summary:"GST pixel state is a material-level control layered into a fixed optical pattern.", tryPrompt:"Switch pixel state and compare uniform with alternating layouts.", limitations:"Switching energy, cycling endurance, and optical contrast depend on stack details and are not modelled.", controlNote:"State is qualitative; the fixed heater is contextual and not a user material control.", materialNote:"GST is a fixed film on fused silica with a fixed heater; layers are never blended." }),
  f({ id:"liquid-crystal", name:"Liquid-crystal metasurface", category:"Optical", tag:"Field-addressed director orientation", color:"#92c8c4", source:"https://doi.org/10.1063/1.4976504", base:4, secondary:25, role:"Liquid-crystal layer", required:true, fixed:true,
    purpose:"show how a liquid-crystal environment can tune the optical response of a patterned surface.", structure:"silicon disks face a liquid-crystal layer between fixed glass and electrode layers.", behaviorText:"an illustrated director orientation changes around the disks when the addressing state changes.", application:"Tunable polarisation-optics demonstrator", usecase:"A small cell helps learners link electric addressing to a changed optical environment.", why:"Liquid crystals introduce reconfiguration without changing the patterned silicon geometry.", variants:[["Planar director","The director is drawn parallel to the surface."],["Tilted director","The director leans through the cell."],["Twisted director","The director rotates from one surface to the other."]], summary:"Fixed silicon disks gain a qualitative tuning degree of freedom from a liquid-crystal layer.", tryPrompt:"Change director orientation while keeping the disks unchanged.", limitations:"Voltage, anchoring, wavelength, and response time are omitted.", controlNote:"Director state is illustrative; electrodes and glass remain fixed context layers.", materialNote:"Silicon disks, liquid crystal, glass, and electrodes are fixed device layers with separate roles." }),
  f({ id:"huygens", name:"Huygens metasurface", category:"Optical", tag:"Paired optical responses shape a wavefront", color:"#95b6e4", source:"https://doi.org/10.1002/adom.201400584", base:4, secondary:22, role:"Fused-silica substrate", required:true, fixed:true,
    purpose:"show a dielectric metasurface that shapes transmitted light with subwavelength elements.", structure:"silicon elements repeat on a fused-silica sheet; their layout encodes a qualitative phase pattern.", behaviorText:"the array can redirect an outgoing wavefront when element response varies across the surface.", application:"Flat beam-steering research optic", usecase:"A flat patterned optic illustrates how a phase ramp can redirect a beam without a curved lens.", why:"Wavefront shaping can be placed in a thin patterned layer.", variants:[["Uniform phase","All elements share one visual pattern."],["Phase ramp","Element pattern changes across one direction."],["Focusing phase","A radial pattern points toward a focal region."]], summary:"A flat dielectric pattern can represent phase control normally associated with shaped optics.", tryPrompt:"Compare the ramp and focusing layouts from above.", limitations:"Efficiency, polarization, and spectral range require electromagnetic simulation and measurement.", controlNote:"Phase layouts are visual encodings, not calculated phase maps.", materialNote:"Silicon elements stay fixed on a glass substrate." }),
  f({ id:"structural-color", name:"Structural-colour pillar array", category:"Optical", tag:"Colour from patterned silicon", color:"#d7b56f", source:"https://doi.org/10.1021/acsphotonics.6b01021", base:4, secondary:22, role:"Fused-silica substrate", required:true, fixed:true,
    purpose:"show that nanoscale pillar geometry can create visible colour without pigments.", structure:"silicon pillars of selected dimensions sit on a transparent glass support in a repeated array.", behaviorText:"geometry changes alter the wavelengths that interact strongly with the surface, represented here as qualitative colour differences.", application:"Pigment-free colour research study", usecase:"A patterned sample is used to explain colour that comes from structure rather than dye.", why:"Colour can be encoded through geometry and potentially avoids a conventional pigment layer.", variants:[["Uniform pillars","One pillar type gives a uniform structural-colour field."],["Two-size mosaic","Two pillar types alternate as a visible pattern."],["Graded pillars","Pillar appearance changes gradually across the sample."]], summary:"Changing a tiny pillar array can change apparent colour through optical structure.", tryPrompt:"Compare the uniform field with the two-size mosaic.", limitations:"Observed colour depends on illumination, viewing angle, dimensions, and fabrication.", controlNote:"Colour swatches are illustrative; no spectral prediction is made.", materialNote:"Silicon pillars are fixed on fused silica and never represented as a mixture." }),
  f({ id:"graphene-absorber", name:"Graphene absorber", category:"Optical", tag:"Gated two-dimensional resonant pattern", color:"#47525b", source:"https://www.nature.com/articles/ncomms8032", base:26, secondary:23, role:"Silicon-nitride spacer", required:true, fixed:true,
    purpose:"introduce a patterned graphene layer whose optical response can be tuned by gating.", structure:"graphene ribbons or disks sit above a silicon-nitride spacer and a fixed gold gate.", behaviorText:"changing the qualitative gate state changes the depicted carrier setting and resonant interaction.", application:"Tunable infrared sensing research", usecase:"A gated device serves as a concept model for an absorber whose resonance can be adjusted electrically.", why:"Graphene adds electrical tunability to a very thin patterned layer.", variants:[["Parallel ribbons","Parallel graphene strips provide the base motif."],["Crossed ribbons","Two strip directions create a crossed pattern."],["Connected disks","Disk-like regions meet through narrow connections."]], summary:"A gated graphene pattern supplies a qualitative tuning handle for infrared absorption.", tryPrompt:"Switch the gate state, then compare strip and disk patterns.", limitations:"Carrier density, loss, spacer thickness, and wavelength are not calculated.", controlNote:"Gate state is a qualitative label; the gold gate remains fixed.", materialNote:"Graphene, silicon nitride, and the fixed gold gate are separate layers, never a blend." }),
  f({ id:"space-time", name:"Space-time modulated metasurface", category:"Electromagnetic", tag:"Travelling bias over resonant cells", color:"#c78a75", source:"https://arxiv.org/abs/2006.06394", base:5, secondary:8, role:"FR-4 support board", required:true, fixed:true,
    purpose:"show the concept of a resonant surface whose bias changes across space and time.", structure:"copper resonator cells are printed on FR-4 with a fixed external bias network.", behaviorText:"a travelling bias pattern is shown as a qualitative sequence rather than a computed frequency conversion.", application:"Nonreciprocal-wave research demonstrator", usecase:"A board is used to explain why temporal modulation is an additional control beyond static geometry.", why:"Time-varying bias can create effects unavailable to a passive static pattern.", variants:[["Static bias","Every cell shows the same bias state."],["Traveling bias","The state advances across the row."],["Reverse traveling bias","The illustrated progression reverses direction."]], summary:"A travelling control pattern extends metasurface design into time as well as space.", tryPrompt:"Toggle bias direction and follow the highlighted sequence across cells.", limitations:"Frequency conversion, stability, and nonreciprocity depend on the drive circuit and are not inferred here.", controlNote:"Bias animation conveys sequence only; it makes no device-performance claim.", materialNote:"Copper is fixed to FR-4; the bias network is a fixed contextual layer." }),
  f({ id:"helmholtz", name:"Helmholtz resonator array", category:"Acoustic", tag:"Cavities coupled through narrow necks", color:"#83c6d8", source:"https://doi.org/10.1103/PhysRevB.99.174109", base:1, secondary:27, role:"Functional air volume", required:true, fixed:true,
    purpose:"show a repeated cavity-and-neck geometry that targets a selected acoustic resonance.", structure:"rigid PA12 walls enclose air cavities, each connected to the outside by a narrow neck.", behaviorText:"air in a neck and cavity can oscillate together, producing a local resonant interaction with sound.", application:"Duct-noise research panel", usecase:"An array is placed beside or inside a test duct to study how cavity geometry changes a narrow acoustic feature.", why:"It packs a familiar bottle-like resonance into a patterned panel.", variants:[["Uniform cavities","Equal cavities repeat in a regular array."],["Staggered volumes","Visible cavity size alternates across rows."],["Shallow cavities","Cavities are drawn with reduced depth."]], summary:"Rigid walls shape functional air into repeated acoustic resonators.", tryPrompt:"Compare equal and staggered cavity layouts.", limitations:"Frequency, damping, flow, and absorption are not calculated.", controlNote:"Cavity style is qualitative geometry only.", materialNote:"PA12 forms the fixed walls; air is the functional medium and not a structural replacement." }),
  f({ id:"acoustic-hologram", name:"Acoustic hologram", category:"Acoustic", tag:"Tile delays shape a sound field", color:"#9fc6df", source:"https://doi.org/10.1038/nature19755", base:17, secondary:27, role:"Functional air channels", required:true, fixed:true,
    purpose:"show how a tiled plate can assign different path delays to parts of a sound wave.", structure:"rigid acrylic tiles contain air channels with different coiled path lengths.", behaviorText:"different path delays can combine downstream to form a chosen qualitative sound-field pattern.", application:"Single-transducer acoustic-patterning concept", usecase:"A patterned plate can be used ahead of one transducer to explain passive acoustic field shaping.", why:"It moves complex phase control from many active channels into a fixed patterned object.", variants:[["Uniform coiled tiles","Every tile uses the same delay path."],["Alternating delay","Two coiled paths alternate across the plate."],["Graded delay","Path appearance changes progressively across tiles."]], summary:"Coiled air paths encode relative acoustic delay in a solid plate.", tryPrompt:"Switch to graded delay and follow the shortest to longest channel.", limitations:"The rendered pattern does not reconstruct or validate a sound field.", controlNote:"Delay labels are ordinal only, not calibrated phase values.", materialNote:"Acrylic tiles bound fixed functional air paths; they are not a material blend." }),
  f({ id:"ventilated-silencer", name:"Ventilated metamaterial silencer", category:"Acoustic", tag:"Noise control around open airflow", color:"#79b3bd", source:"https://arxiv.org/abs/1801.03613", base:1, secondary:27, role:"Ventilation path", required:true, fixed:true,
    purpose:"show a resonant acoustic layout that leaves a route for airflow.", structure:"rigid PA12 channels preserve an open central path while side cavities and necks provide local resonators.", behaviorText:"sound can couple to the side resonators while air still has a visible passage through the panel.", application:"Ventilated enclosure research", usecase:"A duct insert is used to explain why noise control and air passage can coexist in a structured panel.", why:"It makes the airflow constraint visible rather than treating a silencer as a sealed block.", variants:[["One-sided cavities","Resonators sit along one wall."],["Alternating side cavities","Cavities swap from side to side."],["Narrow-neck cavities","The visible connections to cavities become narrower."]], summary:"Side resonators let a panel study sound control while retaining an open air route.", tryPrompt:"Toggle cavity arrangement and keep the central path in view.", limitations:"Flow resistance, noise reduction, and operating band require measurement.", controlNote:"Neck appearance is not a predicted attenuation setting.", materialNote:"PA12 provides rigid walls; air remains the fixed functional medium." }),
  f({ id:"bubble-metascreen", name:"Bubble metascreen", category:"Acoustic", tag:"Soft bubble sheet with guided spacing", color:"#8ecfdd", source:"https://doi.org/10.1103/PhysRevB.91.020301", base:6, secondary:16, role:"Steel guide rails", required:true, fixed:true,
    purpose:"show a compliant bubble-bearing sheet used to study strong acoustic contrast from trapped gas.", structure:"PDMS holds bubble pockets between fixed steel guide rails; the gas inclusions are contextual and not selectable.", behaviorText:"bubble size and spacing can change a qualitative acoustic resonance of the screen.", application:"Underwater acoustic-screen research", usecase:"A bubble-bearing coupon helps explain why a small gas inclusion can interact strongly with sound in liquid.", why:"Gas compressibility gives a simple physical route to pronounced acoustic resonance.", variants:[["Uniform bubbles","Equal bubble pockets repeat in each rail bay."],["Larger bubbles","Pocket size increases across the sheet."],["Alternating bubble sizes","Two bubble sizes alternate along the rails."]], summary:"Trapped gas pockets give a soft screen a geometry-sensitive acoustic response.", tryPrompt:"Compare uniform and alternating bubble sizes.", limitations:"Liquid environment, pressure, bubble lifetime, and resonance are not modelled.", controlNote:"Bubble size is an illustrative geometry state only.", materialNote:"PDMS and steel rails are fixed structural parts; trapped gas is a functional inclusion, not a selectable material." }),
  f({ id:"acoustic-luneburg", name:"Acoustic Luneburg lens", category:"Acoustic", tag:"Graded cells focus incident sound", color:"#75b6cc", source:"https://doi.org/10.1038/s41598-018-34581-7", base:17, secondary:27, role:"Functional air passages", required:true, fixed:true,
    purpose:"show a radially graded acoustic lens that maps incoming sound toward a boundary region.", structure:"rigid acrylic cells contain air passages whose open geometry changes from the centre to the rim.", behaviorText:"the radial grading is used to depict a changing acoustic travel condition through the lens.", application:"Directional acoustic-imaging concept demonstrator", usecase:"A lens coupon can explain how a graded medium can focus a plane sound wave toward its edge.", why:"It translates a curved-lens idea into a patterned, self-supporting cell layout.", variants:[["Graded crosses","Cross-shaped passages change radially."],["Graded rings","Ring-like cells change from centre to edge."],["Asymmetric cross lens","An asymmetric cross-cell grading shows a directional comparison."]], summary:"Radially changing air-cell geometry forms a qualitative acoustic-gradient lens.", tryPrompt:"Inspect the centre-to-rim progression in each lens pattern.", limitations:"Focus position and bandwidth depend on dimensions and are not computed.", controlNote:"Grading is ordinal and qualitative, not an index profile.", materialNote:"Acrylic structures the air passages; air is the functional medium." }),
  f({ id:"thermal-concentrator", name:"Thermal concentrator", category:"Thermal", tag:"Fan sectors guide conductive heat", color:"#d69c73", source:"https://www.nature.com/articles/srep11552", base:5, secondary:6, role:"PDMS insulating sectors", required:true, fixed:true,
    purpose:"show a fan-shaped composite used to guide conductive heat toward a central region.", structure:"copper and PDMS sectors alternate radially around a central region; each sector is fixed in place.", behaviorText:"the contrast between conductive and insulating paths qualitatively redirects the displayed heat-flow arrows.", application:"Thermal-field-manipulation research coupon", usecase:"A flat coupon is heated at its edge to study how patterned sectors reshape a conductive temperature field.", why:"Geometry and material placement provide an intuitive route to steering diffusion.", variants:[["Radial sectors","Alternating sectors point toward the centre."],["Insulated core ring","A ring separates the central region."],["Axial copper strap","One copper path is visually emphasised."]], summary:"Alternating conductive and insulating sectors create a qualitative map for heat-flow guidance.", tryPrompt:"Switch sector layouts and follow the heat-flow arrows as a concept only.", limitations:"No temperature, flux, or concentration factor is calculated; contact resistance matters.", controlNote:"Arrows communicate intended direction, not a thermal simulation.", materialNote:"Copper and PDMS are fixed sectors with separate conductive roles." }),
  f({ id:"thermal-diode", name:"Thermal diode", category:"Thermal", tag:"Directional heat-flow research concept", color:"#e0b27a", source:"https://arxiv.org/abs/2301.10013", base:0, secondary:28, role:"Paraffin phase-change layer", required:true, fixed:true,
    purpose:"present a simplified bilayer concept for direction-dependent thermal transport research.", structure:"a TPU support layer meets a paraffin phase-change layer in a fixed stack.", behaviorText:"reversing the illustrated heat direction changes which layer encounters the thermal transition first.", application:"Thermal-rectification research teaching sample", usecase:"A small bilayer is used to discuss why nonlinear material state can make forward and reverse heat tests differ.", why:"It makes the need for asymmetry and a temperature-dependent material explicit.", variants:[["TPU/paraffin bilayer","A simple two-layer reference stack."],["TPU surface traces","Surface patterning is added to the support layer."],["TPU edge bridges","Bridges alter the illustrated support connectivity."]], summary:"A fixed asymmetric stack introduces the idea of direction-dependent heat transfer.", tryPrompt:"Reverse the heat arrow and identify which layer is encountered first.", limitations:"This is not a validated thermal diode design; rectification needs measured properties and boundary conditions.", controlNote:"Heat direction is conceptual only, with no claimed temperature or flux.", materialNote:"TPU and paraffin are fixed functional layers, not a blended composite." }),
  f({ id:"thermal-emitter", name:"Selective thermal emitter", category:"Thermal", tag:"Patterned metal over dielectric", color:"#e7c46b", source:"https://doi.org/10.1088/2040-8978/16/3/035102", base:13, secondary:12, role:"Alumina spacer", required:true, fixed:true,
    purpose:"show how a patterned metal–dielectric surface can be designed to emit or absorb selectively.", structure:"patterned gold features sit with an alumina spacer above a fixed backing layer.", behaviorText:"pattern geometry is linked qualitatively to wavelength-selective thermal-radiation behaviour.", application:"Infrared-emission research surface", usecase:"A patterned coupon is used to discuss selective emission for sensing or energy-system research.", why:"Patterned layers offer a route to spectral control without relying on bulk material alone.", variants:[["Gold crosses","One cross motif repeats across the surface."],["Dual-size gold crosses","Two cross scales alternate."],["Alumina rings","Dielectric ring features change the visible stack."]], summary:"A patterned metal–dielectric stack can be used to study selective thermal radiation.", tryPrompt:"Compare the single-size and dual-size motif arrangements.", limitations:"Emissivity, angle response, and temperature require spectral measurement.", controlNote:"Motif changes are qualitative and not spectral predictions.", materialNote:"Gold and alumina occupy fixed distinct layers; the backing is contextual and fixed." }),
  f({ id:"magnetic-programmable", name:"Magnetically programmable elastomer", category:"Magnetic", tag:"Fixed magnetization drives soft shape", color:"#7f8ca4", source:"https://arxiv.org/abs/2006.12721", base:6, secondary:30, role:"NdFeB inclusions", required:true, fixed:true,
    purpose:"show an elastomer whose embedded magnetic domains are programmed before use.", structure:"NdFeB inclusions are embedded in a PDMS beam with a fixed illustrated magnetization pattern.", behaviorText:"an external field is represented as a qualitative cue that can bend or reorient the soft beam.", application:"Remote soft-actuator research demonstrator", usecase:"A flexible beam model is used to explain why embedded magnet orientation matters before a field is applied.", why:"Magnetic programming can enable untethered shape change in a soft structure.", variants:[["Rotating panels","Discrete magnetized panels show local orientation."],["Continuous bending beam","A smooth beam shows distributed orientation."],["Segmented beams","Separated segments compare piecewise programming."]], summary:"Programmed magnetic inclusions give a soft beam an external-field response.", tryPrompt:"Change the field direction and compare the programmed orientations.", limitations:"Field strength, magnetization, loading, and deformation are not calculated.", controlNote:"Magnetization is fixed qualitative metadata, never an adjustable engineering value.", materialNote:"NdFeB inclusions are fixed inside PDMS; magnetization is fixed and not a material-control option." }),
  f({ id:"piezo-shunt", name:"Piezo-shunted beam", category:"Electromechanical", tag:"Electrical circuit changes vibration coupling", color:"#cda89e", source:"https://doi.org/10.2514/3.11620", base:29, secondary:2, role:"Aluminium beam", required:true, fixed:true,
    purpose:"show a beam with a piezoelectric patch connected to an external shunt circuit.", structure:"a PZT patch is bonded to an aluminium beam; the circuit is an external fixed context rather than a volume material.", behaviorText:"beam bending is qualitatively coupled to an electrical boundary condition selected by the shunt mode.", application:"Vibration-control research beam", usecase:"A cantilever test piece demonstrates why changing a connected circuit can change structural vibration behaviour.", why:"It joins mechanical and electrical design controls in one compact experiment.", variants:[["Passive RL","A passive resistor–inductor shunt is shown."],["Digital shunt","A controllable electronic shunt is represented."],["Active control concept","An externally powered control concept is labelled."]], summary:"A bonded piezo patch lets an electrical shunt participate in a beam-vibration experiment.", tryPrompt:"Switch shunt modes while keeping the beam geometry fixed.", limitations:"Circuit values, stability, damping, and vibration response require coupled testing.", controlNote:"Shunt mode is a teaching label, not a control-law or performance prediction.", materialNote:"PZT is bonded to an aluminium beam. The external circuit is fixed context, not a third material phase." }),
];
